name: Yolov8v2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.8
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - ultralytics
  - torchaudio
  - scikit-learn
  - openpyxl
  - ipykernel
  - shapely
